/**
 * @fileoverview Volt domain models — shared between extension host and webview.
 *
 * These types describe the core data structures that flow through the message
 * protocol. They MUST remain environment-agnostic (no `vscode`, no DOM APIs).
 *
 * @see design.md — Interfaces / Contracts
 * @see src/shared/protocol.ts — Message wrappers that carry these models
 */

// ---------------------------------------------------------------------------
// HTTP primitives
// ---------------------------------------------------------------------------

/** Supported HTTP methods. */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

/**
 * A single key-value query parameter with an enabled toggle so users can
 * disable individual params without deleting them.
 */
export interface QueryParam {
  readonly key: string;
  readonly value: string;
  /** When false the param is excluded from the final URL. Default: true */
  readonly enabled: boolean;
}

/**
 * Request body — discriminated by `type` so the UI renders the correct editor
 * and the host knows how to serialize it.
 *
 * The `binary` variant (REQ-RB-004) stores the absolute local file path.
 * The host reads the file and sends it as the raw request body.
 */
export type RequestBody =
  | { readonly type: 'json'; readonly content: string }
  | { readonly type: 'text'; readonly content: string }
  | { readonly type: 'form-data'; readonly content: string }
  | { readonly type: 'binary'; readonly filePath: string }
  | { readonly type: 'none' };

// ---------------------------------------------------------------------------
// Core request / response types
// ---------------------------------------------------------------------------

/**
 * A fully-specified HTTP request definition.
 * Stored as YAML inside `.volt/requests/`.
 */
export interface HttpRequestDef {
  /**
   * Stable identifier — used as correlationId anchor and for tab management.
   * UUIDs are recommended; generated by the webview on creation.
   */
  readonly id: string;
  /** Human-readable display name shown in the collection tree. */
  readonly name?: string;
  readonly method: HttpMethod;
  /**
   * URL template — may contain `{{variable}}` placeholders resolved by
   * EnvironmentService before execution.
   */
  readonly url: string;
  readonly headers: Record<string, string>;
  readonly body?: RequestBody;
  readonly queryParams: readonly QueryParam[];
  /** JavaScript code executed BEFORE the request is sent. */
  readonly preScript?: string;
  /** JavaScript code executed AFTER the response is received. */
  readonly postScript?: string;
}

/**
 * Per-phase timing breakdown captured via `diagnostics_channel` hooks.
 * All values are in milliseconds.
 *
 * @see src/extension/services/http-service.ts
 */
export interface TimingBreakdown {
  /** DNS resolution time */
  readonly dns: number;
  /** TCP handshake time */
  readonly tcp: number;
  /** TLS negotiation time (0 for plain HTTP) */
  readonly tls: number;
  /** Time to first byte (from connection established to first response byte) */
  readonly ttfb: number;
  /** Body download time */
  readonly body: number;
  /** Total elapsed wall-clock time */
  readonly total: number;
}

/**
 * The timing phases emitted as progress events during a live request.
 */
export type TimingPhase = 'dns' | 'tcp' | 'tls' | 'ttfb' | 'body';

/**
 * An HTTP response as received by the extension host and forwarded to the
 * webview. The body is always a UTF-8 string (binary responses are base64).
 *
 * REQ-MSG-005: For bodies > 5 MB the body is written to a temp file and
 * `bodyRef` contains the `file:///` URI. The webview renders a "too large"
 * placeholder and offers a download link instead.
 */
export interface HttpResponseDef {
  /** Echoes the `id` of the originating `HttpRequestDef` */
  readonly requestId: string;
  readonly status: number;
  readonly statusText: string;
  readonly headers: Record<string, string>;
  /** Response body as a string (UTF-8 or base64 for binary). Empty when bodyRef is set. */
  readonly body: string;
  /** Byte count of the original body before any truncation */
  readonly bodySize: number;
  /**
   * Whether the body was truncated to the 50 MB safety limit.
   * @see REQ-HTTP-006
   */
  readonly truncated?: boolean;
  /**
   * For bodies > 5 MB: `file:///` URI to the temp file holding the full body.
   * When present, the `body` field is empty and the webview should show a
   * "Response too large to display (X MB). Click to save." placeholder.
   * @see REQ-MSG-005
   */
  readonly bodyRef?: string;
  readonly timing: TimingBreakdown;
}

// ---------------------------------------------------------------------------
// Collection types
// ---------------------------------------------------------------------------

/**
 * A single entry in the collection order array — either a named folder or a
 * direct request file reference.
 */
export type CollectionOrderEntry =
  | { readonly folder: string }
  | { readonly request: string };

/**
 * Represents an individual request item in the collection tree.
 */
export interface CollectionRequestItem {
  readonly kind: 'request';
  /** Relative path inside `.volt/requests/`, without extension */
  readonly path: string;
  readonly name: string;
  readonly method: HttpMethod;
}

/**
 * Represents a folder grouping requests in the collection tree.
 */
export interface CollectionFolderItem {
  readonly kind: 'folder';
  readonly name: string;
  readonly children: readonly CollectionTreeNode[];
}

/** A node in the collection tree — either a folder or a request. */
export type CollectionTreeNode = CollectionFolderItem | CollectionRequestItem;

/**
 * The root collection tree pushed to the webview after loading.
 * Mirrors `.volt/collection.yaml` with enriched metadata from request files.
 */
export interface CollectionTree {
  readonly name: string;
  readonly version: number;
  readonly nodes: readonly CollectionTreeNode[];
}

// ---------------------------------------------------------------------------
// Environment types
// ---------------------------------------------------------------------------

/**
 * A raw environment definition as stored in `.volt/envs/<name>.yaml`.
 */
export interface EnvironmentDef {
  readonly name: string;
  readonly variables: Record<string, string>;
}

/**
 * The fully resolved environment sent to the webview after scope-chain
 * resolution. Variables from higher-priority scopes have already overridden
 * lower-priority ones.
 *
 * Scope priority (high → low): request → collection → project → global
 */
export interface ResolvedEnv {
  /** Active environment name */
  readonly active: string;
  /** All available environment names for the switcher dropdown */
  readonly available: readonly string[];
  /** Merged variable map after scope-chain resolution */
  readonly variables: Record<string, string>;
}
