/**
 * @fileoverview Volt webview ↔ extension-host message protocol.
 *
 * All inter-process communication between the VS Code webview and the
 * extension host MUST use these typed discriminated unions. Every message
 * travels through `vscode.postMessage` / `window.addEventListener('message')`.
 *
 * Naming convention (REQ-MSG-001):
 *   Webview → Host:  `request:*`   (e.g. `request:execute-http`)
 *   Host → Webview:  `response:*`  (direct reply to a request)
 *                    `event:*`     (push notification, no request needed)
 *
 * Design decision: discriminated unions on a `type` string field give
 * exhaustive `switch` type-narrowing at compile time with zero runtime deps.
 *
 * @see design.md — Interfaces / Contracts
 */

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

/**
 * Correlation ID that pairs a request message with its response.
 * Generated by the webview for each logical operation; echoed back by the host.
 */
export type CorrelationId = string;

// ---------------------------------------------------------------------------
// Webview → Host messages  (prefix: `request:*`)
// ---------------------------------------------------------------------------

/**
 * Execute an HTTP request. The host resolves environment variables, fires
 * the request via HttpService, and replies with `response:execute-http` or
 * `response:execute-error`.
 */
export interface ExecuteRequestMessage {
  readonly type: 'request:execute-http';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').HttpRequestDef;
}

/**
 * Cancel an in-flight HTTP request identified by `id` (the correlationId
 * of the matching `request:execute-http` message).
 */
export interface CancelRequestMessage {
  readonly type: 'request:cancel-http';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** correlationId of the `request:execute-http` message to cancel */
    readonly id: string;
  };
}

/**
 * Persist a request definition to `.volt/requests/<path>.yaml`.
 */
export interface SaveRequestMessage {
  readonly type: 'request:save-request';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Relative path inside `.volt/requests/`, e.g. `auth/login` */
    readonly path: string;
    readonly request: import('./models').HttpRequestDef;
  };
}

/**
 * Ask the host to load the full collection tree for the active workspace.
 * The host replies with `response:collection`.
 */
export interface LoadCollectionMessage {
  readonly type: 'request:get-collection';
  readonly correlationId: CorrelationId;
}

/**
 * Ask the host to activate a named environment.
 * The host replies with `event:environment-changed`.
 */
export interface SetEnvironmentMessage {
  readonly type: 'request:set-environment';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Environment name matching a file under `.volt/envs/<name>.yaml` */
    readonly name: string;
  };
}

/**
 * Webview signals it is ready to receive messages (handshake).
 * The host flushes any queued messages after receiving this.
 */
export interface WebviewReadyMessage {
  readonly type: 'request:ready';
  readonly correlationId: CorrelationId;
}

/**
 * Webview requests the host to save arbitrary text content to a file.
 * The host opens a save dialog and writes the content.
 */
export interface SaveToFileMessage {
  readonly type: 'request:save-to-file';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Suggested file name (without path) */
    readonly suggestedName: string;
    /** Content to write */
    readonly content: string;
  };
}

/**
 * Webview requests the host to load a specific request by path.
 * The host replies with `event:load-request` containing the HttpRequestDef.
 */
export interface GetRequestMessage {
  readonly type: 'request:get-request';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Relative path inside `.volt/requests/`, without extension */
    readonly path: string;
  };
}

/**
 * Webview requests the host to create a new environment.
 * The host creates the file and replies with `event:environment-changed`.
 */
export interface CreateEnvironmentMessage {
  readonly type: 'request:create-environment';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Name for the new environment (used as filename) */
    readonly name: string;
  };
}

/**
 * Set or update a single variable in the active environment.
 * The host calls `updateVariables({ [key]: value })` and replies with
 * `event:environment-changed`.
 */
export interface UpdateEnvVarMessage {
  readonly type: 'request:update-env-var';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly key: string;
    readonly value: string;
  };
}

/**
 * Delete a single variable from the active environment.
 * The host replies with `event:environment-changed`.
 */
export interface DeleteEnvVarMessage {
  readonly type: 'request:delete-env-var';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly key: string;
  };
}

/**
 * Delete an entire environment YAML file.
 * The host switches to another env (or empty state) and replies with
 * `event:environment-changed`.
 */
export interface DeleteEnvironmentMessage {
  readonly type: 'request:delete-environment';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly name: string;
  };
}

/**
 * Rename an environment (renames the YAML file).
 * The host replies with `event:environment-changed`.
 */
export interface RenameEnvironmentMessage {
  readonly type: 'request:rename-environment';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly oldName: string;
    readonly newName: string;
  };
}

/**
 * Webview asks the host to open a native file picker and return the selected
 * file path. The host replies with `response:binary-file-picked`.
 * Used by the BinaryBodyPicker component (C-01).
 */
export interface PickBinaryFileMessage {
  readonly type: 'request:pick-binary-file';
  readonly correlationId: CorrelationId;
}

/**
 * Export a single request to a `.volt-request.json` file.
 * The host opens a save dialog and writes the self-contained export file.
 */
export interface ExportRequestMessage {
  readonly type: 'request:export-request';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Relative path inside `.volt/requests/`, without extension */
    readonly path: string;
  };
}

/**
 * Export all requests inside a folder to a `.volt-collection.json` file.
 * The host opens a save dialog and writes the self-contained export file.
 */
export interface ExportFolderMessage {
  readonly type: 'request:export-folder';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Folder name (top-level directory inside `.volt/requests/`) */
    readonly folder: string;
  };
}

/**
 * Import a `.volt-request.json` or `.volt-collection.json` file.
 * The host opens an open dialog, parses the file, and creates the
 * request(s) in the current collection. No payload needed.
 */
export interface ImportMessage {
  readonly type: 'request:import';
  readonly correlationId: CorrelationId;
}

/**
 * Ask the host for the execution history of a saved request.
 * The host replies with `response:history`.
 */
export interface GetHistoryMessage {
  readonly type: 'request:get-history';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Relative path of the saved request, without extension (e.g. `auth/login`) */
    readonly path: string;
  };
}

/**
 * Ask the host to clear all history for a saved request.
 * No reply is sent; the webview should reset local history state immediately.
 */
export interface ClearHistoryMessage {
  readonly type: 'request:clear-history';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly path: string;
  };
}

/**
 * Delete a single entry from a request's execution history by timestamp.
 */
export interface DeleteHistoryEntryMessage {
  readonly type: 'request:delete-history-entry';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly path: string;
    readonly timestamp: string;
  };
}

/**
 * Execute all requests in a folder sequentially (Collection Runner).
 * The host emits `event:runner-progress` after each request and
 * `event:runner-complete` when all requests have been executed.
 */
export interface RunCollectionMessage {
  readonly type: 'request:run-collection';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Top-level folder name inside `.volt/requests/` */
    readonly folder: string;
    /** Delay in milliseconds between requests (default: 0). */
    readonly delay?: number;
  };
}

/**
 * Clear the in-memory cookie jar.
 * No reply is sent.
 */
export interface ClearCookiesMessage {
  readonly type: 'request:clear-cookies';
  readonly correlationId: CorrelationId;
}

/**
 * Fetch an OAuth2 access token via the client_credentials grant.
 * The host POSTs to `tokenUrl` with form-urlencoded credentials and replies
 * with `response:oauth2-token`.
 */
export interface OAuth2GetTokenMessage {
  readonly type: 'request:oauth2-get-token';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly tokenUrl: string;
    readonly clientId: string;
    readonly clientSecret: string;
    readonly scope: string;
    readonly grantType: 'client_credentials' | 'authorization_code';
  };
}

// ---------------------------------------------------------------------------
// WebSocket messages (webview → host)
// ---------------------------------------------------------------------------

/**
 * Open a WebSocket connection to the given URL.
 * The host replies with `event:ws-connected` on success or `event:ws-error`
 * on failure. Supports `{{variable}}` interpolation in the URL.
 */
export interface WsConnectMessage {
  readonly type: 'request:ws-connect';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly url: string;
    readonly headers?: Record<string, string>;
  };
}

/**
 * Send a text frame over the currently open WebSocket connection.
 * The host pushes back `event:ws-message` (direction: sent) to record the
 * outbound frame in the message log.
 */
export interface WsSendMessage {
  readonly type: 'request:ws-send';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly message: string;
  };
}

/**
 * Close the currently open WebSocket connection.
 * The host pushes `event:ws-disconnected` once the socket closes.
 */
export interface WsDisconnectMessage {
  readonly type: 'request:ws-disconnect';
  readonly correlationId: CorrelationId;
}

/** All messages originating from the webview. */
export type HostMessage =
  | ExecuteRequestMessage
  | CancelRequestMessage
  | SaveRequestMessage
  | LoadCollectionMessage
  | SetEnvironmentMessage
  | WebviewReadyMessage
  | GetRequestMessage
  | SaveToFileMessage
  | CreateEnvironmentMessage
  | UpdateEnvVarMessage
  | DeleteEnvVarMessage
  | DeleteEnvironmentMessage
  | RenameEnvironmentMessage
  | PickBinaryFileMessage
  | ExportRequestMessage
  | ExportFolderMessage
  | ImportMessage
  | GetHistoryMessage
  | ClearHistoryMessage
  | DeleteHistoryEntryMessage
  | RunCollectionMessage
  | ClearCookiesMessage
  | OAuth2GetTokenMessage
  | WsConnectMessage
  | WsSendMessage
  | WsDisconnectMessage;

// ---------------------------------------------------------------------------
// Host → Webview messages  (prefix: `response:*` or `event:*`)
// ---------------------------------------------------------------------------

/**
 * Successful HTTP response from `request:execute-http`.
 */
export interface ExecuteResponseMessage {
  readonly type: 'response:execute-http';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').HttpResponseDef;
}

/**
 * Error response for `request:execute-http`. Typed error codes let the UI
 * show actionable feedback (e.g. "Check your network" for dns_error).
 */
export interface ExecuteErrorMessage {
  readonly type: 'response:execute-error';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly message: string;
    /** Machine-readable error code for UI display logic */
    readonly code?: ExecuteErrorCode;
  };
}

export type ExecuteErrorCode =
  | 'timeout'
  | 'cancelled'
  | 'dns_error'
  | 'connection_refused'
  | 'tls_error'
  | 'too_large'
  | 'unknown';

/**
 * Full collection tree pushed after `request:get-collection` or after a
 * file-system change is detected by the FileSystemWatcher.
 */
export interface CollectionLoadedMessage {
  readonly type: 'response:collection';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').CollectionTree;
}

/**
 * Pushed when the active environment changes (user switch or initial load).
 * This is a push event — no explicit request is needed.
 */
export interface EnvironmentChangedMessage {
  readonly type: 'event:environment-changed';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').ResolvedEnv;
}

/**
 * Progress event emitted during an in-flight request (one per timing phase).
 * The webview can use these to render a live timing indicator.
 */
export interface RequestProgressMessage {
  readonly type: 'event:request-progress';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly phase: import('./models').TimingPhase;
    /** Elapsed milliseconds since request was sent */
    readonly elapsed: number;
  };
}

/**
 * Host pushes a saved request definition into the webview builder.
 * Triggered when the user selects a request in the collection tree.
 */
export interface LoadRequestMessage {
  readonly type: 'event:load-request';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').HttpRequestDef;
}

/**
 * Confirmation that a request was saved. Includes the resolved save path
 * so the webview can update its savePath state (e.g. after a "Save As New").
 */
export interface RequestSavedMessage {
  readonly type: 'response:request-saved';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Relative path in .volt/requests/ where the request was saved */
    readonly path: string;
  };
}

/**
 * Pushed when a pre- or post-request script fails.
 * Pre-script errors also produce `response:execute-error`; post-script
 * errors are non-blocking (the HTTP response is still delivered) but
 * should be surfaced visually in the Scripts tab.
 */
export interface ScriptErrorMessage {
  readonly type: 'event:script-error';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Which script phase failed */
    readonly phase: 'pre' | 'post';
    /** Human-readable error description */
    readonly message: string;
  };
}

/**
 * Reply to `request:pick-binary-file`. Contains the selected file path and
 * display name, or `null` if the user cancelled the dialog (C-01).
 */
export interface BinaryFilePickedMessage {
  readonly type: 'response:binary-file-picked';
  readonly correlationId: CorrelationId;
  readonly payload: { readonly path: string; readonly name: string } | null;
}

/**
 * A single entry in a request's execution history.
 */
export interface HistoryEntry {
  readonly timestamp: string;
  readonly method: string;
  readonly url: string;
  readonly status: number;
  readonly statusText: string;
  readonly time: number;
  readonly success: boolean;
  /** Response body (stored for replay in the response viewer) */
  readonly body?: string;
  /** Response headers */
  readonly headers?: Record<string, string>;
}

/**
 * Reply to `request:get-history`. Contains the history entries for the
 * requested path, newest first.
 */
export interface HistoryResponseMessage {
  readonly type: 'response:history';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly path: string;
    readonly entries: HistoryEntry[];
  };
}

/**
 * Assertion results pushed after every request execution.
 * Contains the pass/fail outcome and actual value for each assertion rule.
 */
export interface AssertionResultMessage {
  readonly type: 'event:assertion-results';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly results: ReadonlyArray<import('./models').AssertionResult>;
  };
}

/**
 * Per-request progress event emitted during a collection run.
 * Pushed after each request completes.
 */
export interface RunnerProgressMessage {
  readonly type: 'event:runner-progress';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly index: number;
    readonly total: number;
    readonly requestName: string;
    readonly status: number;
    readonly time: number;
    readonly pass: boolean;
    readonly assertionsPassed: number;
    readonly assertionsTotal: number;
  };
}

/**
 * Emitted when the entire collection run has finished.
 */
export interface RunnerCompleteMessage {
  readonly type: 'event:runner-complete';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly total: number;
    readonly passed: number;
    readonly failed: number;
    readonly totalTime: number;
  };
}

/**
 * Reply to `request:oauth2-get-token`.
 * On success, `accessToken` contains the fetched bearer token.
 * On failure, `error` contains a human-readable description.
 */
export interface OAuth2TokenResponseMessage {
  readonly type: 'response:oauth2-token';
  readonly correlationId: CorrelationId;
  readonly payload:
    | { readonly accessToken: string; readonly expiresIn?: number }
    | { readonly error: string };
}

// ---------------------------------------------------------------------------
// WebSocket events (host → webview)
// ---------------------------------------------------------------------------

/**
 * Pushed when the WebSocket handshake succeeds and the connection is open.
 */
export interface WsConnectedEvent {
  readonly type: 'event:ws-connected';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly url: string;
  };
}

/**
 * Pushed for every inbound text frame and also echoed back for every
 * outbound frame (direction: 'sent') so the message log is self-contained.
 */
export interface WsMessageEvent {
  readonly type: 'event:ws-message';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').WsMessage;
}

/**
 * Pushed when the WebSocket connection closes (normal or abnormal close).
 */
export interface WsDisconnectedEvent {
  readonly type: 'event:ws-disconnected';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly code: number;
    readonly reason: string;
  };
}

/**
 * Pushed when a WebSocket error occurs (connection failure, etc.).
 */
export interface WsErrorEvent {
  readonly type: 'event:ws-error';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly message: string;
  };
}

// ---------------------------------------------------------------------------
// Server-Sent Events (host → webview)
// ---------------------------------------------------------------------------

/**
 * Pushed for every SSE frame received when `Content-Type: text/event-stream`.
 * The webview appends these to a streaming log instead of a static body view.
 */
export interface SseEventMessage {
  readonly type: 'event:sse-event';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').SseEvent;
}

/**
 * Pushed when the SSE stream ends (server close or client abort).
 */
export interface SseEndMessage {
  readonly type: 'event:sse-end';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly reason: string;
  };
}

/** All messages originating from the extension host. */
export type WebviewMessage =
  | ExecuteResponseMessage
  | ExecuteErrorMessage
  | CollectionLoadedMessage
  | EnvironmentChangedMessage
  | RequestProgressMessage
  | LoadRequestMessage
  | RequestSavedMessage
  | ScriptErrorMessage
  | BinaryFilePickedMessage
  | HistoryResponseMessage
  | AssertionResultMessage
  | RunnerProgressMessage
  | RunnerCompleteMessage
  | OAuth2TokenResponseMessage
  | WsConnectedEvent
  | WsMessageEvent
  | WsDisconnectedEvent
  | WsErrorEvent
  | SseEventMessage
  | SseEndMessage;
