/**
 * @fileoverview Volt webview ↔ extension-host message protocol.
 *
 * All inter-process communication between the VS Code webview and the
 * extension host MUST use these typed discriminated unions. Every message
 * travels through `vscode.postMessage` / `window.addEventListener('message')`.
 *
 * Design decision: discriminated unions on a `type` string field give
 * exhaustive `switch` type-narrowing at compile time with zero runtime deps.
 *
 * @see design.md — Interfaces / Contracts
 */

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

/**
 * Correlation ID that pairs a request message with its response.
 * Generated by the webview for each logical operation; echoed back by the host.
 */
export type CorrelationId = string;

// ---------------------------------------------------------------------------
// Webview → Host messages (the webview sends these)
// ---------------------------------------------------------------------------

/**
 * Execute an HTTP request. The host resolves environment variables, fires
 * the request via HttpService, and replies with `execute-response` or
 * `execute-error`.
 */
export interface ExecuteRequestMessage {
  readonly type: 'execute-request';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').HttpRequestDef;
}

/**
 * Cancel an in-flight HTTP request identified by `id` (the correlationId
 * of the matching `execute-request` message).
 */
export interface CancelRequestMessage {
  readonly type: 'cancel-request';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** correlationId of the `execute-request` message to cancel */
    readonly id: string;
  };
}

/**
 * Persist a request definition to `.volt/requests/<path>.yaml`.
 */
export interface SaveRequestMessage {
  readonly type: 'save-request';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Relative path inside `.volt/requests/`, e.g. `auth/login` */
    readonly path: string;
    readonly request: import('./models').HttpRequestDef;
  };
}

/**
 * Ask the host to load the full collection tree for the active workspace.
 * The host replies with `collection-loaded`.
 */
export interface LoadCollectionMessage {
  readonly type: 'load-collection';
  readonly correlationId: CorrelationId;
}

/**
 * Ask the host to activate a named environment.
 * The host replies with `environment-changed`.
 */
export interface SetEnvironmentMessage {
  readonly type: 'set-environment';
  readonly correlationId: CorrelationId;
  readonly payload: {
    /** Environment name matching a file under `.volt/envs/<name>.yaml` */
    readonly name: string;
  };
}

/**
 * Webview signals it is ready to receive messages (handshake).
 * The host flushes any queued messages after receiving this.
 */
export interface WebviewReadyMessage {
  readonly type: 'webview-ready';
  readonly correlationId: CorrelationId;
}

/** All messages originating from the webview. */
export type HostMessage =
  | ExecuteRequestMessage
  | CancelRequestMessage
  | SaveRequestMessage
  | LoadCollectionMessage
  | SetEnvironmentMessage
  | WebviewReadyMessage;

// ---------------------------------------------------------------------------
// Host → Webview messages (the extension host sends these)
// ---------------------------------------------------------------------------

/**
 * Successful HTTP response from `execute-request`.
 */
export interface ExecuteResponseMessage {
  readonly type: 'execute-response';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').HttpResponseDef;
}

/**
 * Error response for `execute-request`. Typed error codes let the UI show
 * actionable feedback (e.g. "Check your network" for dns_error).
 */
export interface ExecuteErrorMessage {
  readonly type: 'execute-error';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly message: string;
    /** Machine-readable error code for UI display logic */
    readonly code?: ExecuteErrorCode;
  };
}

export type ExecuteErrorCode =
  | 'timeout'
  | 'cancelled'
  | 'dns_error'
  | 'connection_refused'
  | 'tls_error'
  | 'too_large'
  | 'unknown';

/**
 * Full collection tree pushed after `load-collection` or after a file-system
 * change is detected by the FileSystemWatcher.
 */
export interface CollectionLoadedMessage {
  readonly type: 'collection-loaded';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').CollectionTree;
}

/**
 * Pushed when the active environment changes (user switch or initial load).
 */
export interface EnvironmentChangedMessage {
  readonly type: 'environment-changed';
  readonly correlationId: CorrelationId;
  readonly payload: import('./models').ResolvedEnv;
}

/**
 * Progress event emitted during an in-flight request (one per timing phase).
 * The webview can use these to render a live timing indicator.
 */
export interface RequestProgressMessage {
  readonly type: 'request-progress';
  readonly correlationId: CorrelationId;
  readonly payload: {
    readonly phase: import('./models').TimingPhase;
    /** Elapsed milliseconds since request was sent */
    readonly elapsed: number;
  };
}

/** All messages originating from the extension host. */
export type WebviewMessage =
  | ExecuteResponseMessage
  | ExecuteErrorMessage
  | CollectionLoadedMessage
  | EnvironmentChangedMessage
  | RequestProgressMessage;
